version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'agora-aegon-portfolios'
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
